import index from '../content/lessons.index.json'
import { unitOrder } from './units'

/** A video embedded at the end of a lesson. */
export interface LessonVideo {
  title: string
  /** The id from the YouTube URL: youtube.com/watch?v=XXXXXXXXXXX */
  youtubeId: string
  /** Optional: jump straight to a timestamp, in seconds. */
  start?: number
}

/** An outside link shown under «للاستزادة» at the end of a lesson. */
export interface LessonResource {
  title: string
  url: string
  /** One short line saying why this link is worth opening. */
  note?: string
}

/** The YAML block at the top of every lesson file. */
export interface LessonMeta {
  title: string
  /** One sentence a beginner understands, shown on the card and under the title. */
  description: string
  /** Which unit it belongs to. Must match an `id` in src/lib/units.ts. */
  unit: string
  /** Position inside the whole curriculum. Lower comes first. */
  order: number
  /** Rough reading time in minutes, used to set expectations on the card. */
  minutes: number
  emoji: string
  /** 2 to 4 short Arabic keywords shown on the lesson card. */
  tags?: string[]
  videos?: LessonVideo[]
  resources?: LessonResource[]
}

/**
 * A lesson without its body.
 *
 * The body lives in src/lib/lesson-content.ts, imported only by the routes that
 * actually render it. The home page needs a title and a description for each of
 * the thirty-four cards; before the split it pulled all thirty-four lesson
 * bodies into the entry chunk to get them.
 */
export interface Lesson extends LessonMeta {
  /** URL segment, taken from the file name: ikhfa-haqiqi.md -> "ikhfa-haqiqi" */
  slug: string
}

/**
 * Every lesson, in curriculum order (by unit first, then by `order`).
 *
 * Generated by `npm run content:build` from the frontmatter of every file in
 * src/content/lessons/, which runs before both `dev` and `build`. Adding a
 * lesson is still just adding a file.
 */
export const lessons: Lesson[] = (index as Lesson[])
  .slice()
  .sort((a, b) => unitOrder(a.unit) - unitOrder(b.unit) || a.order - b.order)

const BY_SLUG = new Map(lessons.map((lesson) => [lesson.slug, lesson]))

export function getLesson(slug: string): Lesson | undefined {
  return BY_SLUG.get(slug)
}

/** Lessons of one unit, in order. */
export function lessonsOfUnit(unitId: string): Lesson[] {
  return lessons.filter((lesson) => lesson.unit === unitId)
}

/** The lesson before and after this one, for the «السابق / التالي» links. */
export function neighbours(slug: string): { prev?: Lesson; next?: Lesson } {
  const index = lessons.findIndex((lesson) => lesson.slug === slug)
  if (index === -1) return {}
  return { prev: lessons[index - 1], next: lessons[index + 1] }
}
